on:
  push:
    branches: master

name: Publish to NPM

jobs:
  publish:
    name: publish
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key:
            ${{ matrix.node-version }}--${{ runner.OS
            }}-build-${{hashFiles('package.json', 'yarn.lock') }}
      - if: steps.cache-modules.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
      - run: yarn build
      - uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
